# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-15 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('work_exp', models.CharField(max_length=2)),
                ('anaytics_in_exp', models.CharField(max_length=2)),
                ('current_location', models.CharField(max_length=100)),
                ('corrected_location', models.CharField(max_length=100)),
                ('nearest_city', models.CharField(max_length=100)),
                ('preferred_location', models.CharField(max_length=100)),
                ('ctc', models.CharField(max_length=10)),
                ('current_employer', models.CharField(max_length=100)),
                ('current_designation', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=100)),
                ('UG_Course', models.CharField(max_length=100)),
                ('UG_Institute_Name', models.CharField(max_length=100)),
                ('UG_Passing_Year', models.CharField(max_length=4)),
                ('PG_Course', models.CharField(max_length=100)),
                ('Correct_PG_Course', models.CharField(max_length=100)),
                ('PG_Institute_Name', models.CharField(max_length=100)),
                ('trier_1', models.CharField(max_length=5)),
                ('PG_Passing_Year', models.CharField(max_length=4)),
                ('Post_PG_Course', models.CharField(max_length=100)),
                ('Correct_Post_PG', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
