# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-15 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_filter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Correct_PG_Course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Correct_Post_PG',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='PG_Course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='PG_Institute_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='PG_Passing_Year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='Post_PG_Course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='UG_Course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='UG_Institute_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='UG_Passing_Year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='anaytics_in_exp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='ctc',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_designation',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_employer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='trier_1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_exp',
            field=models.CharField(max_length=10),
        ),
    ]
