# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_filter_app', '0002_auto_20180415_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'employees'},
        ),
    ]
