# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_filter_app', '0003_auto_20180416_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'employee'},
        ),
    ]
